// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: src/api/traffic/proto/.proto

package traffic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficService_GetTotalMbps_FullMethodName = "/traffic.TrafficService/GetTotalMbps"
	TrafficService_GetSplitMbps_FullMethodName = "/traffic.TrafficService/GetSplitMbps"
)

// TrafficServiceClient is the client API for TrafficService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficServiceClient interface {
	GetTotalMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTotalMbpsResponse, error)
	GetSplitMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSplitMbpsResponse, error)
}

type trafficServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficServiceClient(cc grpc.ClientConnInterface) TrafficServiceClient {
	return &trafficServiceClient{cc}
}

func (c *trafficServiceClient) GetTotalMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTotalMbpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalMbpsResponse)
	err := c.cc.Invoke(ctx, TrafficService_GetTotalMbps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) GetSplitMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSplitMbpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSplitMbpsResponse)
	err := c.cc.Invoke(ctx, TrafficService_GetSplitMbps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficServiceServer is the server API for TrafficService service.
// All implementations must embed UnimplementedTrafficServiceServer
// for forward compatibility.
type TrafficServiceServer interface {
	GetTotalMbps(context.Context, *emptypb.Empty) (*GetTotalMbpsResponse, error)
	GetSplitMbps(context.Context, *emptypb.Empty) (*GetSplitMbpsResponse, error)
	mustEmbedUnimplementedTrafficServiceServer()
}

// UnimplementedTrafficServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficServiceServer struct{}

func (UnimplementedTrafficServiceServer) GetTotalMbps(context.Context, *emptypb.Empty) (*GetTotalMbpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalMbps not implemented")
}
func (UnimplementedTrafficServiceServer) GetSplitMbps(context.Context, *emptypb.Empty) (*GetSplitMbpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSplitMbps not implemented")
}
func (UnimplementedTrafficServiceServer) mustEmbedUnimplementedTrafficServiceServer() {}
func (UnimplementedTrafficServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrafficServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficServiceServer will
// result in compilation errors.
type UnsafeTrafficServiceServer interface {
	mustEmbedUnimplementedTrafficServiceServer()
}

func RegisterTrafficServiceServer(s grpc.ServiceRegistrar, srv TrafficServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrafficServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficService_ServiceDesc, srv)
}

func _TrafficService_GetTotalMbps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).GetTotalMbps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_GetTotalMbps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).GetTotalMbps(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_GetSplitMbps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).GetSplitMbps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_GetSplitMbps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).GetSplitMbps(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficService_ServiceDesc is the grpc.ServiceDesc for TrafficService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "traffic.TrafficService",
	HandlerType: (*TrafficServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotalMbps",
			Handler:    _TrafficService_GetTotalMbps_Handler,
		},
		{
			MethodName: "GetSplitMbps",
			Handler:    _TrafficService_GetSplitMbps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/api/traffic/proto/.proto",
}
