// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: src/api/traffic/proto/.proto

package traffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalMbpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mbps          float64                `protobuf:"fixed64,1,opt,name=mbps,proto3" json:"mbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalMbpsResponse) Reset() {
	*x = GetTotalMbpsResponse{}
	mi := &file_src_api_traffic_proto__proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalMbpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalMbpsResponse) ProtoMessage() {}

func (x *GetTotalMbpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_traffic_proto__proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalMbpsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalMbpsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_traffic_proto__proto_rawDescGZIP(), []int{0}
}

func (x *GetTotalMbpsResponse) GetMbps() float64 {
	if x != nil {
		return x.Mbps
	}
	return 0
}

type GetSplitMbpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Down          float64                `protobuf:"fixed64,1,opt,name=down,proto3" json:"down,omitempty"`
	Up            float64                `protobuf:"fixed64,2,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSplitMbpsResponse) Reset() {
	*x = GetSplitMbpsResponse{}
	mi := &file_src_api_traffic_proto__proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSplitMbpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSplitMbpsResponse) ProtoMessage() {}

func (x *GetSplitMbpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_traffic_proto__proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSplitMbpsResponse.ProtoReflect.Descriptor instead.
func (*GetSplitMbpsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_traffic_proto__proto_rawDescGZIP(), []int{1}
}

func (x *GetSplitMbpsResponse) GetDown() float64 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *GetSplitMbpsResponse) GetUp() float64 {
	if x != nil {
		return x.Up
	}
	return 0
}

var File_src_api_traffic_proto__proto protoreflect.FileDescriptor

const file_src_api_traffic_proto__proto_rawDesc = "" +
	"\n" +
	"\x1csrc/api/traffic/proto/.proto\x12\atraffic\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x14GetTotalMbpsResponse\x12\x12\n" +
	"\x04mbps\x18\x01 \x01(\x01R\x04mbps\":\n" +
	"\x14GetSplitMbpsResponse\x12\x12\n" +
	"\x04down\x18\x01 \x01(\x01R\x04down\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\x01R\x02up2\x9e\x01\n" +
	"\x0eTrafficService\x12E\n" +
	"\fGetTotalMbps\x12\x16.google.protobuf.Empty\x1a\x1d.traffic.GetTotalMbpsResponse\x12E\n" +
	"\fGetSplitMbps\x12\x16.google.protobuf.Empty\x1a\x1d.traffic.GetSplitMbpsResponseB\x1fZ\x1dsrc/api/traffic/proto;trafficb\x06proto3"

var (
	file_src_api_traffic_proto__proto_rawDescOnce sync.Once
	file_src_api_traffic_proto__proto_rawDescData []byte
)

func file_src_api_traffic_proto__proto_rawDescGZIP() []byte {
	file_src_api_traffic_proto__proto_rawDescOnce.Do(func() {
		file_src_api_traffic_proto__proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_api_traffic_proto__proto_rawDesc), len(file_src_api_traffic_proto__proto_rawDesc)))
	})
	return file_src_api_traffic_proto__proto_rawDescData
}

var file_src_api_traffic_proto__proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_api_traffic_proto__proto_goTypes = []any{
	(*GetTotalMbpsResponse)(nil), // 0: traffic.GetTotalMbpsResponse
	(*GetSplitMbpsResponse)(nil), // 1: traffic.GetSplitMbpsResponse
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
}
var file_src_api_traffic_proto__proto_depIdxs = []int32{
	2, // 0: traffic.TrafficService.GetTotalMbps:input_type -> google.protobuf.Empty
	2, // 1: traffic.TrafficService.GetSplitMbps:input_type -> google.protobuf.Empty
	0, // 2: traffic.TrafficService.GetTotalMbps:output_type -> traffic.GetTotalMbpsResponse
	1, // 3: traffic.TrafficService.GetSplitMbps:output_type -> traffic.GetSplitMbpsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_api_traffic_proto__proto_init() }
func file_src_api_traffic_proto__proto_init() {
	if File_src_api_traffic_proto__proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_api_traffic_proto__proto_rawDesc), len(file_src_api_traffic_proto__proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_api_traffic_proto__proto_goTypes,
		DependencyIndexes: file_src_api_traffic_proto__proto_depIdxs,
		MessageInfos:      file_src_api_traffic_proto__proto_msgTypes,
	}.Build()
	File_src_api_traffic_proto__proto = out.File
	file_src_api_traffic_proto__proto_goTypes = nil
	file_src_api_traffic_proto__proto_depIdxs = nil
}
