// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: src/api/monitoring/proto/.proto

package monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalMbpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mbps          float64                `protobuf:"fixed64,1,opt,name=mbps,proto3" json:"mbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalMbpsResponse) Reset() {
	*x = GetTotalMbpsResponse{}
	mi := &file_src_api_monitoring_proto__proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalMbpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalMbpsResponse) ProtoMessage() {}

func (x *GetTotalMbpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_monitoring_proto__proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalMbpsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalMbpsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_monitoring_proto__proto_rawDescGZIP(), []int{0}
}

func (x *GetTotalMbpsResponse) GetMbps() float64 {
	if x != nil {
		return x.Mbps
	}
	return 0
}

type GetSplitMbpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Down          float64                `protobuf:"fixed64,1,opt,name=down,proto3" json:"down,omitempty"`
	Up            float64                `protobuf:"fixed64,2,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSplitMbpsResponse) Reset() {
	*x = GetSplitMbpsResponse{}
	mi := &file_src_api_monitoring_proto__proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSplitMbpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSplitMbpsResponse) ProtoMessage() {}

func (x *GetSplitMbpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_monitoring_proto__proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSplitMbpsResponse.ProtoReflect.Descriptor instead.
func (*GetSplitMbpsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_monitoring_proto__proto_rawDescGZIP(), []int{1}
}

func (x *GetSplitMbpsResponse) GetDown() float64 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *GetSplitMbpsResponse) GetUp() float64 {
	if x != nil {
		return x.Up
	}
	return 0
}

type GetConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   int32                  `protobuf:"varint,1,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionsResponse) Reset() {
	*x = GetConnectionsResponse{}
	mi := &file_src_api_monitoring_proto__proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionsResponse) ProtoMessage() {}

func (x *GetConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_monitoring_proto__proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_monitoring_proto__proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectionsResponse) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type GetCPUPercentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float64                `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCPUPercentResponse) Reset() {
	*x = GetCPUPercentResponse{}
	mi := &file_src_api_monitoring_proto__proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCPUPercentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCPUPercentResponse) ProtoMessage() {}

func (x *GetCPUPercentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_monitoring_proto__proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCPUPercentResponse.ProtoReflect.Descriptor instead.
func (*GetCPUPercentResponse) Descriptor() ([]byte, []int) {
	return file_src_api_monitoring_proto__proto_rawDescGZIP(), []int{3}
}

func (x *GetCPUPercentResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type GetMemoryPercentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float64                `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryPercentResponse) Reset() {
	*x = GetMemoryPercentResponse{}
	mi := &file_src_api_monitoring_proto__proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryPercentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryPercentResponse) ProtoMessage() {}

func (x *GetMemoryPercentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_monitoring_proto__proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryPercentResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryPercentResponse) Descriptor() ([]byte, []int) {
	return file_src_api_monitoring_proto__proto_rawDescGZIP(), []int{4}
}

func (x *GetMemoryPercentResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

var File_src_api_monitoring_proto__proto protoreflect.FileDescriptor

const file_src_api_monitoring_proto__proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/api/monitoring/proto/.proto\x12\n" +
	"monitoring\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x14GetTotalMbpsResponse\x12\x12\n" +
	"\x04mbps\x18\x01 \x01(\x01R\x04mbps\":\n" +
	"\x14GetSplitMbpsResponse\x12\x12\n" +
	"\x04down\x18\x01 \x01(\x01R\x04down\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\x01R\x02up\":\n" +
	"\x16GetConnectionsResponse\x12 \n" +
	"\vconnections\x18\x01 \x01(\x05R\vconnections\"1\n" +
	"\x15GetCPUPercentResponse\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent\"4\n" +
	"\x18GetMemoryPercentResponse\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent2\x93\x03\n" +
	"\x11MonitoringService\x12H\n" +
	"\fGetTotalMbps\x12\x16.google.protobuf.Empty\x1a .monitoring.GetTotalMbpsResponse\x12H\n" +
	"\fGetSplitMbps\x12\x16.google.protobuf.Empty\x1a .monitoring.GetSplitMbpsResponse\x12L\n" +
	"\x0eGetConnections\x12\x16.google.protobuf.Empty\x1a\".monitoring.GetConnectionsResponse\x12J\n" +
	"\rGetCPUPercent\x12\x16.google.protobuf.Empty\x1a!.monitoring.GetCPUPercentResponse\x12P\n" +
	"\x10GetMemoryPercent\x12\x16.google.protobuf.Empty\x1a$.monitoring.GetMemoryPercentResponseB%Z#src/api/monitoring/proto;monitoringb\x06proto3"

var (
	file_src_api_monitoring_proto__proto_rawDescOnce sync.Once
	file_src_api_monitoring_proto__proto_rawDescData []byte
)

func file_src_api_monitoring_proto__proto_rawDescGZIP() []byte {
	file_src_api_monitoring_proto__proto_rawDescOnce.Do(func() {
		file_src_api_monitoring_proto__proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_api_monitoring_proto__proto_rawDesc), len(file_src_api_monitoring_proto__proto_rawDesc)))
	})
	return file_src_api_monitoring_proto__proto_rawDescData
}

var file_src_api_monitoring_proto__proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_api_monitoring_proto__proto_goTypes = []any{
	(*GetTotalMbpsResponse)(nil),     // 0: monitoring.GetTotalMbpsResponse
	(*GetSplitMbpsResponse)(nil),     // 1: monitoring.GetSplitMbpsResponse
	(*GetConnectionsResponse)(nil),   // 2: monitoring.GetConnectionsResponse
	(*GetCPUPercentResponse)(nil),    // 3: monitoring.GetCPUPercentResponse
	(*GetMemoryPercentResponse)(nil), // 4: monitoring.GetMemoryPercentResponse
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_src_api_monitoring_proto__proto_depIdxs = []int32{
	5, // 0: monitoring.MonitoringService.GetTotalMbps:input_type -> google.protobuf.Empty
	5, // 1: monitoring.MonitoringService.GetSplitMbps:input_type -> google.protobuf.Empty
	5, // 2: monitoring.MonitoringService.GetConnections:input_type -> google.protobuf.Empty
	5, // 3: monitoring.MonitoringService.GetCPUPercent:input_type -> google.protobuf.Empty
	5, // 4: monitoring.MonitoringService.GetMemoryPercent:input_type -> google.protobuf.Empty
	0, // 5: monitoring.MonitoringService.GetTotalMbps:output_type -> monitoring.GetTotalMbpsResponse
	1, // 6: monitoring.MonitoringService.GetSplitMbps:output_type -> monitoring.GetSplitMbpsResponse
	2, // 7: monitoring.MonitoringService.GetConnections:output_type -> monitoring.GetConnectionsResponse
	3, // 8: monitoring.MonitoringService.GetCPUPercent:output_type -> monitoring.GetCPUPercentResponse
	4, // 9: monitoring.MonitoringService.GetMemoryPercent:output_type -> monitoring.GetMemoryPercentResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_api_monitoring_proto__proto_init() }
func file_src_api_monitoring_proto__proto_init() {
	if File_src_api_monitoring_proto__proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_api_monitoring_proto__proto_rawDesc), len(file_src_api_monitoring_proto__proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_api_monitoring_proto__proto_goTypes,
		DependencyIndexes: file_src_api_monitoring_proto__proto_depIdxs,
		MessageInfos:      file_src_api_monitoring_proto__proto_msgTypes,
	}.Build()
	File_src_api_monitoring_proto__proto = out.File
	file_src_api_monitoring_proto__proto_goTypes = nil
	file_src_api_monitoring_proto__proto_depIdxs = nil
}
