// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: src/api/monitoring/proto/.proto

package monitoring

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitoringService_GetTotalMbps_FullMethodName     = "/monitoring.MonitoringService/GetTotalMbps"
	MonitoringService_GetSplitMbps_FullMethodName     = "/monitoring.MonitoringService/GetSplitMbps"
	MonitoringService_GetConnections_FullMethodName   = "/monitoring.MonitoringService/GetConnections"
	MonitoringService_GetCPUPercent_FullMethodName    = "/monitoring.MonitoringService/GetCPUPercent"
	MonitoringService_GetMemoryPercent_FullMethodName = "/monitoring.MonitoringService/GetMemoryPercent"
)

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitoringServiceClient interface {
	GetTotalMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTotalMbpsResponse, error)
	GetSplitMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSplitMbpsResponse, error)
	GetConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetConnectionsResponse, error)
	GetCPUPercent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCPUPercentResponse, error)
	GetMemoryPercent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMemoryPercentResponse, error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) GetTotalMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTotalMbpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalMbpsResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetTotalMbps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetSplitMbps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSplitMbpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSplitMbpsResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetSplitMbps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionsResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetCPUPercent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCPUPercentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCPUPercentResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetCPUPercent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetMemoryPercent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMemoryPercentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoryPercentResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetMemoryPercent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitoringServiceServer is the server API for MonitoringService service.
// All implementations must embed UnimplementedMonitoringServiceServer
// for forward compatibility.
type MonitoringServiceServer interface {
	GetTotalMbps(context.Context, *emptypb.Empty) (*GetTotalMbpsResponse, error)
	GetSplitMbps(context.Context, *emptypb.Empty) (*GetSplitMbpsResponse, error)
	GetConnections(context.Context, *emptypb.Empty) (*GetConnectionsResponse, error)
	GetCPUPercent(context.Context, *emptypb.Empty) (*GetCPUPercentResponse, error)
	GetMemoryPercent(context.Context, *emptypb.Empty) (*GetMemoryPercentResponse, error)
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoringServiceServer struct{}

func (UnimplementedMonitoringServiceServer) GetTotalMbps(context.Context, *emptypb.Empty) (*GetTotalMbpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalMbps not implemented")
}
func (UnimplementedMonitoringServiceServer) GetSplitMbps(context.Context, *emptypb.Empty) (*GetSplitMbpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSplitMbps not implemented")
}
func (UnimplementedMonitoringServiceServer) GetConnections(context.Context, *emptypb.Empty) (*GetConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnections not implemented")
}
func (UnimplementedMonitoringServiceServer) GetCPUPercent(context.Context, *emptypb.Empty) (*GetCPUPercentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCPUPercent not implemented")
}
func (UnimplementedMonitoringServiceServer) GetMemoryPercent(context.Context, *emptypb.Empty) (*GetMemoryPercentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemoryPercent not implemented")
}
func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}
func (UnimplementedMonitoringServiceServer) testEmbeddedByValue()                           {}

// UnsafeMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServiceServer will
// result in compilation errors.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

func _MonitoringService_GetTotalMbps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetTotalMbps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetTotalMbps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetTotalMbps(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetSplitMbps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetSplitMbps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetSplitMbps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetSplitMbps(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetConnections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetCPUPercent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetCPUPercent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetCPUPercent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetCPUPercent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetMemoryPercent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetMemoryPercent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetMemoryPercent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetMemoryPercent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitoringService_ServiceDesc is the grpc.ServiceDesc for MonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotalMbps",
			Handler:    _MonitoringService_GetTotalMbps_Handler,
		},
		{
			MethodName: "GetSplitMbps",
			Handler:    _MonitoringService_GetSplitMbps_Handler,
		},
		{
			MethodName: "GetConnections",
			Handler:    _MonitoringService_GetConnections_Handler,
		},
		{
			MethodName: "GetCPUPercent",
			Handler:    _MonitoringService_GetCPUPercent_Handler,
		},
		{
			MethodName: "GetMemoryPercent",
			Handler:    _MonitoringService_GetMemoryPercent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/api/monitoring/proto/.proto",
}
