// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: src/api/config/proto/.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClientRequest) Reset() {
	*x = AddClientRequest{}
	mi := &file_src_api_config_proto__proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientRequest) ProtoMessage() {}

func (x *AddClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_config_proto__proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientRequest.ProtoReflect.Descriptor instead.
func (*AddClientRequest) Descriptor() ([]byte, []int) {
	return file_src_api_config_proto__proto_rawDescGZIP(), []int{0}
}

func (x *AddClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	File          []byte                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClientResponse) Reset() {
	*x = AddClientResponse{}
	mi := &file_src_api_config_proto__proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientResponse) ProtoMessage() {}

func (x *AddClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_config_proto__proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientResponse.ProtoReflect.Descriptor instead.
func (*AddClientResponse) Descriptor() ([]byte, []int) {
	return file_src_api_config_proto__proto_rawDescGZIP(), []int{1}
}

func (x *AddClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddClientResponse) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_src_api_config_proto__proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_config_proto__proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_src_api_config_proto__proto_rawDescGZIP(), []int{2}
}

func (x *DeleteClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_src_api_config_proto__proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_config_proto__proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_src_api_config_proto__proto_rawDescGZIP(), []int{3}
}

func (x *DeleteClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerResponse) Reset() {
	*x = StartServerResponse{}
	mi := &file_src_api_config_proto__proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerResponse) ProtoMessage() {}

func (x *StartServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_config_proto__proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerResponse.ProtoReflect.Descriptor instead.
func (*StartServerResponse) Descriptor() ([]byte, []int) {
	return file_src_api_config_proto__proto_rawDescGZIP(), []int{4}
}

func (x *StartServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_src_api_config_proto__proto protoreflect.FileDescriptor

const file_src_api_config_proto__proto_rawDesc = "" +
	"\n" +
	"\x1bsrc/api/config/proto/.proto\x12\x06config\x1a\x1bgoogle/protobuf/empty.proto\"\"\n" +
	"\x10AddClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x11AddClientResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x02 \x01(\fR\x04file\"%\n" +
	"\x13DeleteClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteClientResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x13StartServerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xe0\x01\n" +
	"\rConfigService\x12@\n" +
	"\tAddClient\x12\x18.config.AddClientRequest\x1a\x19.config.AddClientResponse\x12I\n" +
	"\fDeleteClient\x12\x1b.config.DeleteClientRequest\x1a\x1c.config.DeleteClientResponse\x12B\n" +
	"\vStartServer\x12\x16.google.protobuf.Empty\x1a\x1b.config.StartServerResponseB\x1dZ\x1bsrc/api/config/proto;configb\x06proto3"

var (
	file_src_api_config_proto__proto_rawDescOnce sync.Once
	file_src_api_config_proto__proto_rawDescData []byte
)

func file_src_api_config_proto__proto_rawDescGZIP() []byte {
	file_src_api_config_proto__proto_rawDescOnce.Do(func() {
		file_src_api_config_proto__proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_api_config_proto__proto_rawDesc), len(file_src_api_config_proto__proto_rawDesc)))
	})
	return file_src_api_config_proto__proto_rawDescData
}

var file_src_api_config_proto__proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_api_config_proto__proto_goTypes = []any{
	(*AddClientRequest)(nil),     // 0: config.AddClientRequest
	(*AddClientResponse)(nil),    // 1: config.AddClientResponse
	(*DeleteClientRequest)(nil),  // 2: config.DeleteClientRequest
	(*DeleteClientResponse)(nil), // 3: config.DeleteClientResponse
	(*StartServerResponse)(nil),  // 4: config.StartServerResponse
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_src_api_config_proto__proto_depIdxs = []int32{
	0, // 0: config.ConfigService.AddClient:input_type -> config.AddClientRequest
	2, // 1: config.ConfigService.DeleteClient:input_type -> config.DeleteClientRequest
	5, // 2: config.ConfigService.StartServer:input_type -> google.protobuf.Empty
	1, // 3: config.ConfigService.AddClient:output_type -> config.AddClientResponse
	3, // 4: config.ConfigService.DeleteClient:output_type -> config.DeleteClientResponse
	4, // 5: config.ConfigService.StartServer:output_type -> config.StartServerResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_api_config_proto__proto_init() }
func file_src_api_config_proto__proto_init() {
	if File_src_api_config_proto__proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_api_config_proto__proto_rawDesc), len(file_src_api_config_proto__proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_api_config_proto__proto_goTypes,
		DependencyIndexes: file_src_api_config_proto__proto_depIdxs,
		MessageInfos:      file_src_api_config_proto__proto_msgTypes,
	}.Build()
	File_src_api_config_proto__proto = out.File
	file_src_api_config_proto__proto_goTypes = nil
	file_src_api_config_proto__proto_depIdxs = nil
}
